### ISSUE TITLE
Hard coded variable for population size in fun.R

### ISSUE THREAD

**Issue by smhoban** [mnavascues/microsatABC-IM#1]
The total population size in the structure input file is hard coded as "680" in the file fun.R.

This might be better to set as a variable such as  tot_num_ind<-length(data[,1])

Then you can have 
data_as_loci <- data.frame(apply(data, 2, function(x) paste(x[seq(1,tot_num_ind,2)],x[seq(2,tot_num_ind,2)],sep="/")))
instead of
data_as_loci <- data.frame(apply(data, 2, function(x) paste(x[seq(1,680,2)],x[seq(2,680,2)],sep="/")))

Thanks for an overall really great set of code- so far its flexible and is working well

**Comment by mnavascues** [comment]
Thanks, it has been corrected now.
